// Generated by gencpp from file pepper_tracking/image_return.msg
// DO NOT EDIT!


#ifndef PEPPER_TRACKING_MESSAGE_IMAGE_RETURN_H
#define PEPPER_TRACKING_MESSAGE_IMAGE_RETURN_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace pepper_tracking
{
template <class ContainerAllocator>
struct image_return_
{
  typedef image_return_<ContainerAllocator> Type;

  image_return_()
    : found(false)
    , image_name()  {
    }
  image_return_(const ContainerAllocator& _alloc)
    : found(false)
    , image_name(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _found_type;
  _found_type found;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _image_name_type;
  _image_name_type image_name;





  typedef boost::shared_ptr< ::pepper_tracking::image_return_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pepper_tracking::image_return_<ContainerAllocator> const> ConstPtr;

}; // struct image_return_

typedef ::pepper_tracking::image_return_<std::allocator<void> > image_return;

typedef boost::shared_ptr< ::pepper_tracking::image_return > image_returnPtr;
typedef boost::shared_ptr< ::pepper_tracking::image_return const> image_returnConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pepper_tracking::image_return_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pepper_tracking::image_return_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace pepper_tracking

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'pepper_tracking': ['/home/mis/follow_ws/src/pepper_tracking/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::pepper_tracking::image_return_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pepper_tracking::image_return_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pepper_tracking::image_return_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pepper_tracking::image_return_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pepper_tracking::image_return_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pepper_tracking::image_return_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pepper_tracking::image_return_<ContainerAllocator> >
{
  static const char* value()
  {
    return "68cd02969b39e785e4cdf1cf76db231c";
  }

  static const char* value(const ::pepper_tracking::image_return_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x68cd02969b39e785ULL;
  static const uint64_t static_value2 = 0xe4cdf1cf76db231cULL;
};

template<class ContainerAllocator>
struct DataType< ::pepper_tracking::image_return_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pepper_tracking/image_return";
  }

  static const char* value(const ::pepper_tracking::image_return_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pepper_tracking::image_return_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool found\n\
string image_name\n\
";
  }

  static const char* value(const ::pepper_tracking::image_return_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pepper_tracking::image_return_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.found);
      stream.next(m.image_name);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct image_return_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pepper_tracking::image_return_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pepper_tracking::image_return_<ContainerAllocator>& v)
  {
    s << indent << "found: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.found);
    s << indent << "image_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.image_name);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PEPPER_TRACKING_MESSAGE_IMAGE_RETURN_H
